name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: I want to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe your ideal solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any workarounds you've tried?
